backend:
  name: git-gateway
  branch: master # Your default branch (main/master)
media_folder: "images" # Where images will be stored
public_folder: "/images"
collections:
  - name: "books"
    label: "Books"
    folder: "_books" # Jekyll will process files here
    create: true # Allow creating new books
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Cover Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }
      - { label: "Genre", name: "genre", widget: "string" }